components/fieldset/fieldset.tsx
next.config.js
package.json
yarn.lock

chore: remove next css

---

lib/components/sidebar/index.tsx
pages/_app.tsx

docs: improve scrollbar on windows

---

lib/components/attributes/attributes.tsx
lib/components/controls.tsx
lib/components/icons/toggle.tsx
lib/components/layout.tsx
lib/components/sidebar/active-catalog.tsx
lib/components/sidebar/index.tsx
lib/components/sidebar/side-item.tsx
lib/components/sidebar/tabbar-mobile.tsx
pages/_app.tsx
pages/docs/index.js

docs: improve the layout of mobile screen

---

components/button-dropdown/button-dropdown.tsx
components/checkbox/checkbox-group.tsx
components/checkbox/checkbox.tsx
components/fieldset/fieldset-group.tsx
components/fieldset/fieldset.tsx
components/radio/radio.tsx
components/select/select-context.ts
components/select/select-dropdown.tsx
components/select/select-option.tsx
components/select/select.tsx
components/shared/dropdown.tsx
components/spacer/spacer.tsx
components/styles/theme-provider/theme-provider.tsx
components/tabs/tabs.tsx
components/utils/use-click-anywhere.ts
components/utils/use-click-away.ts
components/utils/use-portal.ts
components/utils/use-resize.ts
components/utils/use-warning.ts

Add hooks and remove some duplicate functions

---

pages/docs/getting-started/installation.mdx

docs: add example project for create-react-app

---

pages/docs/getting-started/installation.mdx

docs: fix typo

---

components/modal/modal.tsx
components/toast/toast-item.tsx
components/utils/use-body-scroll.ts
lib/components/layout.tsx
lib/components/playground/index.tsx
lib/components/sidebar/active-catalog.tsx
lib/components/sidebar/index.tsx
lib/components/sidebar/side-item.tsx
pages/_app.tsx

Improve styles & add body scroll hooks

---

lib/components/sidebar/side-item.tsx

docs: remove text-transform on active link

---

components/input/input.tsx

fix(input): fix value update from controlled component

---

components/input/input-icon-clear.tsx
components/input/input.tsx
pages/docs/components/input.mdx

feat(input): add custom width to fit more layouts

---

components/index.ts

Export all theme types. Theme types may be required when developers customize styles.
1. Define all vars of `Theme`:
```ts
import { ZeitUIThemes } from '@zeit-ui/react'
const myStyles: ZeitUIThemes = () => {
// ...
}
```
2. Just define what you need:
```ts
import { ZeitUIThemes } from '@zeit-ui/react'
const myStyles: Partial<ZeitUIThemes> = () => {
// ...
}
```

fix(theme): export types of theme

---

README.md

Added a new showcase: Implement of ZEIT's Dashboard

chore: add showcase

---

components/styles/themes/dark.ts
components/styles/themes/default.ts
components/styles/themes/index.ts
components/toast/use-toast.tsx
lib/components/displays/colors-data.ts
lib/components/displays/colors.tsx
lib/components/playground/index.tsx
package.json
pages/docs/customization/colors.mdx
pages/docs/customization/themes.mdx
yarn.lock

docs: add color cards

---

pages/docs/customization/themes.mdx

docs: fix switch themes code

---

components/input/input-block-label.tsx
components/input/input.tsx
pages/docs/components/input.mdx

feat(input): allow user to customize label content

---

components/dot/dot.tsx
components/input/input.tsx

fix: fix alignment issues caused by line-height on safari

---

components/link/link.tsx
pages/docs/components/link.mdx

feat(link): forward ref for next/link compatibility

---

components/badge/badge.tsx

fix(badge): fix the foregroud color is covered in dark mode

---

components/auto-complete/auto-complete.tsx
components/button-dropdown/button-dropdown.tsx
components/checkbox/checkbox.tsx
components/collapse/collapse.tsx
components/fieldset/fieldset-footer.tsx
components/fieldset/fieldset.tsx
components/file-tree/tree.tsx
components/input/input.tsx
components/modal/modal.tsx
components/radio/radio.tsx
components/select/select.tsx
components/table/table.tsx
components/tabs/tabs.tsx

fix(types): fix ignore native types when export types manually

---

lib/components/displays/colors-data.ts
lib/components/displays/colors.tsx
pages/en-us/customization/themes.mdx
pages/zh-cn/customization/themes.mdx

docs(themes): show all types of theme definitions

---

lib/components/menu/menu-sticker.tsx

1. Pages and side-bar data always follow `pathname`.
2. Redirect to default page if switch languages.
3. Redirect to default page if tabbar is clicked.

docs: don't redirect to default page if pathname existed

---

components/image/image.tsx
pages/en-us/components/image.mdx
pages/zh-cn/components/image.mdx

feat(image): add a prop to control max duration of image animation

---

lib/components/sidebar/active-link.tsx
lib/components/sidebar/side-item.tsx

docs: reduce the weight of component name in chinese title

---

lib/components/playground/index.tsx

docs(playground): show title on copy icon

---

components/display/display.tsx
components/image/image.tsx

fix: remove the background caused by the line-height of img

---

components/styles/theme-provider/theme-provider.tsx
components/utils/types.d.ts
package.json

feat(themes): deep merge themes by default

---

components/card/card.tsx
components/card/styles.ts
components/utils/prop-types.ts
pages/en-us/components/card.mdx
pages/zh-cn/components/card.mdx

feat(card): append types to card

---

.eslintignore
components/tag/tag.tsx
pages/en-us/components/tag.mdx
pages/zh-cn/components/tag.mdx

feat(tag): append types to tag component

---

components/display/display.tsx
components/image/image-browser-https-icon.tsx
components/image/image-browser.tsx
components/image/image.tsx
components/image/index.ts
components/image/styles.ts
pages/en-us/components/image.mdx
pages/zh-cn/components/image.mdx

feat(image): add browser style

---

components/image/image-browser.tsx

fix(image): limit the max width of the image on browser mode

---

components/avatar/avatar-group.tsx
components/avatar/avatar.tsx
components/avatar/index.ts
pages/en-us/components/avatar.mdx
pages/zh-cn/components/avatar.mdx

feat(avatar): use group to display multiple avatars

---

components/select/select.tsx
components/shared/dropdown.tsx
lib/components/controls.tsx
lib/components/layout.tsx
lib/components/menu/index.tsx
lib/components/menu/menu-sticker.tsx
lib/use-dom-clean.ts
package.json
pages/_app.tsx
pages/_document.tsx
pages/en-us/components/input.mdx
pages/en-us/components/select.mdx
pages/zh-cn/components/select.mdx
yarn.lock

docs: keep the theme perferences for visitors

---

components/styles/themes/dark.ts

feat(link): display colors for links in dark mode

---

.circleci/config.yml
.jest.config.js
components/avatar/__tests__/__snapshots__/index.test.tsx.snap
components/avatar/__tests__/index.test.tsx
components/avatar/avatar.tsx
components/avatar/constants.ts
components/capacity/__tests__/__snapshots__/index.test.tsx.snap
components/capacity/__tests__/index.test.tsx
package.json

ci: report coverage to codecov.io

---

.jest.config.js
components/button/__tests__/__snapshots__/index.test.tsx.snap
components/button/__tests__/index.test.tsx
components/button/button.drip.tsx
components/button/button.tsx
package.json
tests/.babelrc.js
tests/utils.ts
yarn.lock

test(button): add testcase

---

components/button-dropdown/__tests__/__snapshots__/index.test.tsx.snap
components/button-dropdown/__tests__/index.test.tsx
tests/utils.ts

test(button-dropdown): add testcase

---

.codecov.yml
components/card/__tests__/__snapshots__/index.test.tsx.snap
components/card/__tests__/index.test.tsx
components/card/index.ts

test(card): add testcase

---

components/checkbox/__tests__/__snapshots__/group.test.tsx.snap
components/checkbox/__tests__/__snapshots__/index.test.tsx.snap
components/checkbox/__tests__/group.test.tsx
components/checkbox/__tests__/index.test.tsx
components/checkbox/checkbox-context.ts
components/checkbox/checkbox.tsx

test(checkbox): add testcase

---

components/auto-complete/__tests__/__snapshots__/index.test.tsx.snap
components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
components/auto-complete/__tests__/index.test.tsx
components/auto-complete/__tests__/search.test.tsx
components/auto-complete/auto-complete-context.ts
components/auto-complete/auto-complete-dropdown.tsx
components/auto-complete/auto-complete-item.tsx
components/auto-complete/auto-complete.tsx

test(auto-complete): add testcase

---

components/code/__tests__/__snapshots__/index.test.tsx.snap
components/code/__tests__/index.test.tsx
components/styles/css-baseline/css-baseline.tsx

test(code): add testcase

---

package.json
scripts/webpack.config.js

resolved #110 
1. About 3kb - 10kb reduction per package. (gzipped)
2. `index.js` file reduced by 4kb.
3. For users of lib `styled-jsx`, the application will reduced by 8kb - 10kb.(gzipped)
4. No change in current bundle time.
5. The new bundle mode starts working after version `0.0.1-beta.29`.

build: move styled-jsx to dependencies

---

components/dot/__tests__/__snapshots__/index.test.tsx.snap
components/dot/__tests__/index.test.tsx
components/fieldset/__tests__/__snapshots__/index.test.tsx.snap
components/fieldset/__tests__/group.test.tsx
components/fieldset/__tests__/index.test.tsx
components/fieldset/fieldset.tsx
components/file-tree/__tests__/__snapshots__/index.test.tsx.snap
components/file-tree/__tests__/index.test.tsx
components/image/__tests__/__snapshots__/browser.test.tsx.snap
components/image/__tests__/__snapshots__/index.test.tsx.snap
components/image/__tests__/browser.test.tsx
components/image/__tests__/index.test.tsx

test: add testcase

---

.circleci/config.yml
components/display/display.tsx

fix(display): hide shadow on dark mode

---

components/tag/__tests__/__snapshots__/index.test.tsx.snap
components/tag/__tests__/index.test.tsx
components/tag/tag.tsx

test(tag): add testcase

---

components/image/image-browser.tsx

feat(image): forward ref for image browser

---

components/slider/slider.tsx
pages/en-us/components/slider.mdx
pages/zh-cn/components/slider.mdx

fix(slider): fix excessive offset when sync custom value

---

components/input/__tests__/__snapshots__/index.test.tsx.snap
components/input/__tests__/index.test.tsx
components/input/__tests__/use-input.test.tsx
components/input/input-icon-clear.tsx
components/input/input.tsx
components/keyboard/__tests__/__snapshots__/index.test.tsx.snap
components/keyboard/__tests__/index.test.tsx
components/link/__tests__/__snapshots__/index.test.tsx.snap
components/link/__tests__/index.test.tsx
components/loading/__tests__/__snapshots__/index.test.tsx.snap
components/loading/__tests__/index.test.tsx
components/modal/__tests__/__snapshots__/index.test.tsx.snap
components/modal/__tests__/index.test.tsx
components/modal/__tests__/use-modal.test.tsx
components/modal/modal-context.ts
components/modal/modal.tsx

test(input): add testcase

---

package.json

fix(module): fix the default export module file

---

components/card/__tests__/__snapshots__/footer.test.tsx.snap
components/card/__tests__/__snapshots__/index.test.tsx.snap
components/card/__tests__/footer.test.tsx
components/card/card-footer.tsx
components/card/card.tsx
components/card/index.ts
pages/en-us/components/card.mdx
pages/zh-cn/components/card.mdx

feat(card): add footer component

---

components/radio/__tests__/__snapshots__/group.test.tsx.snap
components/radio/__tests__/__snapshots__/index.test.tsx.snap
components/radio/__tests__/group.test.tsx
components/radio/__tests__/index.test.tsx
components/radio/radio-group.tsx
components/radio/radio.tsx
components/row/__tests__/__snapshots__/index.test.tsx.snap
components/row/__tests__/index.test.tsx
components/select/__tests__/__snapshots__/index.test.tsx.snap
components/select/__tests__/index.test.tsx
components/select/select-option.tsx

test: add test cases

---

components/image/__tests__/index.test.tsx
components/image/image.tsx
pages/en-us/components/display.mdx
pages/en-us/components/image.mdx
pages/zh-cn/components/display.mdx
pages/zh-cn/components/image.mdx

feat(image): auto scale image when width is too small

---

components/modal/__tests__/__snapshots__/index.test.tsx.snap
components/modal/modal-title.tsx
components/modal/modal-wrapper.tsx
components/shared/backdrop.tsx
components/styles/themes/dark.ts
lib/components/menu/menu-sticker.tsx
lib/components/sidebar/tabbar-mobile.tsx

fix(modal): fix styles to follow design guide

---

components/index.ts
components/modal/__tests__/use-modal.test.tsx
components/modal/modal-action.tsx
components/text/__tests__/__snapshots__/index.test.tsx.snap
components/text/__tests__/index.test.tsx
components/utils/__tests__/calculations.test.tsx
components/utils/index.ts
package.json

chore: add test cases and export utils

---

components/tooltip/__test__/index.test.tsx

test(tooltip): add testcase

---

README.md
package.json
pages/en-us/guide/introduction.mdx
pages/zh-cn/guide/introduction.mdx
yarn.lock

docs: rename the referenced ZEIT brand name in docs

---

components/styles/__tests__/__snapshots__/baseline.test.tsx.snap
components/styles/__tests__/__snapshots__/theme-provider.test.tsx.snap
components/styles/__tests__/baseline.test.tsx
components/styles/__tests__/theme-provider.test.tsx

test(styles): add testcase

---

components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
components/input/__tests__/__snapshots__/index.test.tsx.snap
components/input/input.tsx
components/styles/__tests__/__snapshots__/baseline.test.tsx.snap
components/styles/css-baseline/css-baseline.tsx
components/textarea/__tests__/__snapshots__/index.test.tsx.snap
components/textarea/textarea.tsx
pages/_app.tsx

fix: fix input styles and baseline

---

components/styles/__tests__/__snapshots__/baseline.test.tsx.snap
components/styles/css-baseline/css-baseline.tsx

Link icons through CSS variables: zeit-ui/react-icons#2

feat(icons): link icons through CSS variables

---

components/button/button.drip.tsx
components/fieldset/fieldset-context.ts
components/fieldset/fieldset-group.tsx
components/fieldset/fieldset.tsx
components/file-tree/tree-context.ts
components/file-tree/tree-file.tsx
components/modal/modal-action.tsx
components/modal/modal-context.ts

test: remove unused default-values

---

.jest.config.js
components/styles/__tests__/__snapshots__/baseline.test.tsx.snap
components/styles/css-baseline/css-baseline.tsx
components/text/__tests__/__snapshots__/index.test.tsx.snap
components/text/child.tsx
components/text/text.tsx
pages/en-us/components/text.mdx
pages/zh-cn/components/text.mdx

feat(text): add blockquote

---

components/input/__tests__/__snapshots__/index.test.tsx.snap
components/input/__tests__/__snapshots__/password.test.tsx.snap
components/input/__tests__/index.test.tsx
components/input/__tests__/password.test.tsx
components/input/index.ts
components/input/input-icon.tsx
components/input/input-props.ts
components/input/input.tsx
components/input/password-icon.tsx
components/input/password.tsx
pages/en-us/components/input.mdx
pages/zh-cn/components/input.mdx

feat(input): add password

---

components/card/__tests__/__snapshots__/footer.test.tsx.snap
components/card/__tests__/__snapshots__/index.test.tsx.snap
components/card/__tests__/index.test.tsx
components/card/card-content.tsx
components/card/card.tsx
components/card/index.ts
pages/en-us/components/card.mdx
pages/zh-cn/components/card.mdx

feat(card): extract content wrapper

---

components/styles/__tests__/__snapshots__/theme-provider.test.tsx.snap
components/text/__tests__/__snapshots__/index.test.tsx.snap
components/text/__tests__/index.test.tsx
components/text/child.tsx
components/text/text.tsx
pages/en-us/components/text.mdx
pages/zh-cn/components/text.mdx

feat(text): add size to specify the text size

---

components/fieldset/__tests__/__snapshots__/index.test.tsx.snap
components/fieldset/__tests__/index.test.tsx
components/fieldset/fieldset-content.tsx
components/fieldset/fieldset-footer.tsx
components/fieldset/fieldset.tsx
components/fieldset/index.ts
pages/en-us/components/fieldset.mdx
pages/zh-cn/components/fieldset.mdx

feat(fieldset): extract content wrapper

---

components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
components/input/__tests__/__snapshots__/index.test.tsx.snap
components/input/__tests__/__snapshots__/password.test.tsx.snap
components/input/input.tsx

fix(input): fix color of fill text

---

components/note/__tests__/__snapshots__/index.test.tsx.snap
components/note/note.tsx
components/toast/__tests__/__snapshots__/index.test.tsx.snap
components/toast/toast-item.tsx

fix: prevent main color change in special types

---

components/badge/__tests__/__snapshots__/anchor.test.tsx.snap
components/badge/__tests__/__snapshots__/index.test.tsx.snap
components/badge/__tests__/anchor.test.tsx
components/badge/__tests__/index.test.tsx
components/badge/badge-anchor.tsx
components/badge/badge.tsx
components/badge/index.ts
pages/en-us/components/badge.mdx
pages/zh-cn/components/badge.mdx

feat(badge): supoort to anchor with other components

---

components/shared/__tests__/__snapshots__/backdrop.test.tsx.snap
components/shared/__tests__/__snapshots__/dropdown.test.tsx.snap
components/shared/__tests__/__snapshots__/transition.test.tsx.snap
components/shared/__tests__/backdrop.test.tsx
components/shared/__tests__/dropdown.test.tsx
components/shared/__tests__/transition.test.tsx
components/shared/dropdown.tsx

Maybe these components can also be exported.

test(shared): add testcases for shared components

---

.github/CONTRIBUTING.md

chore(gh): update contributing guide

---

lib/components/layout.tsx
lib/components/menu/index.tsx
lib/components/playground/index.ts
lib/components/playground/playground.tsx
pages/_document.tsx

docs: optimize time of page load

---

lib/components/playground/editor.tsx
lib/components/playground/playground.tsx

fix(playground): fix arrow icon does not work correctly on webkit

---

components/button/__tests__/__snapshots__/icon.test.tsx.snap
components/button/__tests__/icon.test.tsx
components/button/__tests__/index.test.tsx
components/button/button-icon.tsx
components/button/button.tsx
components/button/index.ts
components/button/styles.ts
components/toast/__tests__/__snapshots__/index.test.tsx.snap
components/toast/__tests__/index.test.tsx
pages/en-us/components/button.mdx
pages/zh-cn/components/button.mdx

resolved #178 
this feature will be released in version `v1.1.0`.

feat(button): support to display icons in button

---

rollup.config.js

This profile of `rollup` is not actually in use, currently, `rollup` has no obvious advantage over `webpack`.

build: split output by module

---

pages/en-us/components/image.mdx

fix: fixed typo

---

components/modal/__tests__/__snapshots__/index.test.tsx.snap
components/modal/__tests__/index.test.tsx
components/modal/modal-wrapper.tsx
components/modal/modal.tsx
package.json
pages/en-us/components/modal.mdx
pages/zh-cn/components/modal.mdx

Request from [spectrum](https://spectrum.chat/zeit-ui/general/is-there-a-way-to-set-the-width-of-a-modal~c9b97461-12e3-4370-83f6-d931491e6e96).

feat(modal): custom width and className

---

components/input/__tests__/index.test.tsx
components/input/input.tsx
package.json

fix(input): fix ref type of input forwarding

---

components/shared/backdrop.tsx

fix: fix backdrop layer prevent default behavior

---

components/grid/__tests__/__snapshots__/index.test.tsx.snap
components/grid/grid-container.tsx
components/grid/grid.tsx
tests/__mocks__/styled-jsx/css.js

fix(grid): fix side effects of global styles

---

components/popover/__tests__/__snapshots__/index.test.tsx.snap
components/tooltip/tooltip.tsx

fix(tooltip): fix autowrap errors for elements wrapped by tooltip

---

components/code/__tests__/__snapshots__/index.test.tsx.snap
components/code/__tests__/index.test.tsx
components/code/code.tsx

chore: remove deprecated props

---

components/input/input.tsx

fix(input): fix icon event is cached incorrectly

---

components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
components/input/__tests__/__snapshots__/index.test.tsx.snap
components/input/__tests__/__snapshots__/password.test.tsx.snap
components/input/input.tsx
pages/en-us/components/input.mdx
pages/zh-cn/components/input.mdx

fix(input): fix default width of Input cannot shrink under flex

---

components/tabs/__tests__/__snapshots__/index.test.tsx.snap
components/tabs/__tests__/index.test.tsx
components/tabs/tabs.tsx
pages/en-us/components/tabs.mdx
pages/zh-cn/components/tabs.mdx

feat(tabs): provide a prop for the display of divider

---

pages/en-us/guide/server-render.mdx
pages/zh-cn/guide/server-render.mdx

docs: fix out of date API in the server-render example

docs: fix out of date API in the server-render example

---

components/button-group/__tests__/__snapshots__/index.test.tsx.snap
components/button/__tests__/__snapshots__/icon.test.tsx.snap
components/button/__tests__/__snapshots__/index.test.tsx.snap
components/button/__tests__/index.test.tsx
components/button/button.tsx
components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
pages/en-us/components/button.mdx
pages/en-us/components/input.mdx
pages/en-us/components/link.mdx
pages/zh-cn/components/button.mdx
pages/zh-cn/components/input.mdx
pages/zh-cn/components/link.mdx

feat(button): forward the ref of the original element

---

components/user/__tests__/index.test.tsx
components/user/user.tsx
pages/en-us/components/user.mdx
pages/zh-cn/components/user.mdx

Sorry for using google translation for editing Chinese docs :pray: :bow: 
close: #225

feat(user): provide a prop for alt text

---

components/checkbox/__tests__/__snapshots__/group.test.tsx.snap
components/checkbox/__tests__/__snapshots__/index.test.tsx.snap
components/checkbox/__tests__/group.test.tsx
components/checkbox/__tests__/index.test.tsx
components/checkbox/checkbox-group.tsx
components/checkbox/checkbox.icon.tsx
components/checkbox/checkbox.tsx
pages/en-us/components/checkbox.mdx
pages/zh-cn/components/checkbox.mdx

feat(checkbox): add support of different sizes

---

components/select/__tests__/__snapshots__/index.test.tsx.snap
components/select/__tests__/__snapshots__/multiple.test.tsx.snap
components/select/__tests__/index.test.tsx
components/select/__tests__/multiple.test.tsx
components/select/select-context.ts
components/select/select-multiple-value.tsx
components/select/select-option.tsx
components/select/select.tsx
components/shared/dropdown.tsx
components/use-current-state/__tests__/current-state.test.tsx
components/use-current-state/use-current-state.ts
components/utils/collections.ts
components/utils/use-dom-observer.ts
pages/en-us/components/select.mdx
pages/en-us/components/use-current-state.mdx
pages/zh-cn/components/select.mdx
pages/zh-cn/components/use-current-state.mdx

feat(select): handle multiple selections

---

lib/components/customization/codes.tsx
lib/components/header.tsx
lib/components/layout.tsx
pages/en-us/customization/index.tsx
pages/en-us/guide/colors.mdx
pages/en-us/guide/installation.mdx
pages/en-us/guide/introduction.mdx
pages/zh-cn/customization/index.tsx
pages/zh-cn/guide/colors.mdx
pages/zh-cn/guide/installation.mdx
pages/zh-cn/guide/introduction.mdx

docs: optimize document site

---

components/auto-complete/__tests__/__snapshots__/index.test.tsx.snap
components/auto-complete/auto-complete-dropdown.tsx
components/auto-complete/auto-complete-item.tsx
components/auto-complete/auto-complete.tsx
pages/en-us/components/auto-complete.mdx
pages/zh-cn/components/auto-complete.mdx

feat(auto-complete): disable dropdown follow parent width

---

components/auto-complete/auto-complete-item.tsx
components/select/__tests__/__snapshots__/index.test.tsx.snap
components/select/__tests__/__snapshots__/multiple.test.tsx.snap
components/select/__tests__/multiple.test.tsx
components/select/select-option.tsx
components/select/select.tsx
components/shared/__tests__/__snapshots__/ellipsis.test.tsx.snap
components/shared/__tests__/ellipsis.test.tsx
components/shared/ellipsis.tsx

fix: fix placeholder does not show ellipsis

---

components/button-group/__tests__/__snapshots__/index.test.tsx.snap
components/button/__tests__/__snapshots__/icon.test.tsx.snap
components/button/button-loading.tsx
components/button/button.tsx
components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
pages/en-us/components/button.mdx
pages/zh-cn/components/button.mdx

fix: fix loading is not display under auto width

---

lib/components/controls.tsx

fix(controls): fix option content not center vertically

---

components/auto-complete/__tests__/use-input.test.tsx
components/input/use-input.ts

feat(use-input): compatible with components of non-standed events

---

components/radio/__tests__/group.test.tsx
components/radio/radio-context.ts
components/radio/radio-group.tsx
components/radio/radio.tsx

feat(radio): support for number type

---

pages/en-us/guide/colors.mdx
pages/en-us/guide/installation.mdx
pages/en-us/guide/introduction.mdx
pages/en-us/guide/server-render.mdx
pages/en-us/guide/themes.mdx

I read through the en-us guides and have updated/fixed some of the grammar.

docs: grammar updates to en-us guides

---

components/grid/__tests__/__snapshots__/index.test.tsx.snap
components/grid/__tests__/index.test.tsx
components/grid/basic-item.tsx
components/select/__tests__/__snapshots__/multiple.test.tsx.snap
pages/en-us/components/grid.mdx
pages/zh-cn/components/grid.mdx

feat(grid): hide item when unit size is 0

---

components/modal/__tests__/__snapshots__/index.test.tsx.snap
components/modal/modal-actions.tsx
components/modal/modal-content.tsx
components/modal/modal-title.tsx
components/modal/modal-wrapper.tsx
components/modal/modal.tsx
components/shared/__tests__/__snapshots__/backdrop.test.tsx.snap
components/shared/__tests__/backdrop.test.tsx
components/shared/backdrop.tsx

fix(modal): fix height constraint of modal

---

components/grid/__tests__/__snapshots__/index.test.tsx.snap
components/grid/basic-item.tsx
components/select/__tests__/__snapshots__/multiple.test.tsx.snap

fix(grid): remove unreasonable attribute

---

pages/en-us/components/snippet.mdx
pages/en-us/components/toast.mdx
pages/zh-cn/components/snippet.mdx
pages/zh-cn/components/toast.mdx

docs: improve APIs of components

---

components/auto-complete/auto-complete-item.tsx
components/select/__tests__/__snapshots__/index.test.tsx.snap
components/select/__tests__/__snapshots__/multiple.test.tsx.snap
components/select/select-option.tsx
components/select/select.tsx
components/shared/__tests__/__snapshots__/ellipsis.test.tsx.snap
components/shared/__tests__/ellipsis.test.tsx
components/shared/ellipsis.tsx

fix(ellipsis): set the height of ellipsis manually

---

components/modal/__tests__/__snapshots__/index.test.tsx.snap
components/modal/modal-wrapper.tsx
components/shared/__tests__/__snapshots__/backdrop.test.tsx.snap
components/shared/backdrop.tsx

feat(modal): optimize the animation of layer

---

lib/components/controls.tsx

docs: format unique abbreviations

---

components/modal/__tests__/__snapshots__/index.test.tsx.snap
components/modal/modal-wrapper.tsx
components/shared/__tests__/__snapshots__/backdrop.test.tsx.snap
components/shared/backdrop.tsx
lib/components/menu/menu-links.tsx

- Optimize the style of `Modal`.
- The behavior of the component has not changed.
- `shared/backdrop` is currently only quoted by `Modal`.
resolved #300

feat(modal): optimize the max width, height and alignment of layer

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-feature-request.md
.github/ISSUE_TEMPLATE/3-docs.md
.github/ISSUE_TEMPLATE/3-styles.md
.github/ISSUE_TEMPLATE/4-docs.md
.github/PULL_REQUEST_TEMPLATE.md

chore(gh): update GitHub templates

---

.github/ISSUE_TEMPLATE/config.yml

chore(gh): add help support template

---

components/button/button.tsx
components/image/__tests__/browser.test.tsx
components/snippet/__tests__/__snapshots__/index.test.tsx.snap
components/snippet/__tests__/index.test.tsx
components/snippet/snippet.tsx

fix(snippet): remove space when the symbol is empty

---

lib/components/playground/playground.tsx
lib/components/playground/title.tsx
pages/en-us/components/badge.mdx
pages/zh-cn/components/badge.mdx

docs: add example for custom colors

---

components/tabs/__tests__/index.test.tsx
components/tabs/tabs-context.ts
components/tabs/tabs-item.tsx
components/tabs/tabs.tsx
pages/en-us/components/tabs.mdx
pages/zh-cn/components/tabs.mdx

feat(tabs): sync the label and set value to required

---

components/input/input.tsx
pages/en-us/components/input.mdx
pages/zh-cn/components/input.mdx

fix(input): always synchronize external value and ignore changes

---

components/input/input-icon-clear.tsx
components/input/input.tsx

fix(typo): visibale -> visible

---

components/textarea/__tests__/__snapshots__/index.test.tsx.snap
components/textarea/textarea.tsx
pages/en-us/components/textarea.mdx
pages/zh-cn/components/textarea.mdx

fix(textarea): imperative api same as input

---

components/modal/__tests__/__snapshots__/index.test.tsx.snap
components/modal/modal-content.tsx
components/select/select-dropdown.tsx
components/select/select.tsx
components/shared/__tests__/dropdown.test.tsx
components/shared/dropdown.tsx
components/utils/use-portal.ts
pages/en-us/components/select.mdx
pages/zh-cn/components/select.mdx

feat(dropdown): allow dropdown to set the specified container

---

components/link/__tests__/__snapshots__/index.test.tsx.snap
components/link/link.tsx

fix(link): fix hard-coded background color

---

components/description/description.tsx

style(description): fix title font-weight

---

pages/en-us/components/link.mdx
pages/zh-cn/components/link.mdx

docs(link): fix duplicate examples

---

components/table/__tests__/index.test.tsx
components/table/table-column.tsx
components/table/table-context.ts
components/table/table.tsx

This change is to fix an error, but it may cause changes in user expectations, so it is only merged into branch *rc* at present.
fixed #359

fix(table): fix column's props are not tracked

---

components/table/__tests__/index.test.tsx
components/table/table-column.tsx

fix(table): children of column should be kept in sync

---

components/checkbox/checkbox.tsx

fix(checkbox): fix export type

---

.github/CONTRIBUTING.md
pages/en-us/components/image.mdx

1. Fixed types of Image component's height & width attributes which solves the issue (#373).
2. Also, fixed a slight typo in CONTRIBUTING.md i.e., `agian → again`.

docs(image): fix image types

---

pages/_app.tsx

docs: improve og-title

---

components/avatar/__tests__/index.test.tsx
next.config.js
package.json
pages/en-us/components/toast.mdx
pages/en-us/index.js
pages/index.ts
pages/zh-cn/components/textarea.mdx
pages/zh-cn/components/toast.mdx
pages/zh-cn/index.js
yarn.lock

docs: improve redirects

---

components/modal/__tests__/__snapshots__/index.test.tsx.snap
components/modal/modal-action.tsx
components/modal/modal-content.tsx
components/modal/modal-subtitle.tsx
components/modal/modal-wrapper.tsx
components/modal/modal.tsx
components/shared/__tests__/__snapshots__/backdrop.test.tsx.snap
components/shared/__tests__/backdrop.test.tsx
components/shared/backdrop.tsx
lib/components/menu/menu-sticker.tsx
pages/en-us/components/modal.mdx

fix(modal): fix typography and alignment on mobile

---

components/css-baseline/__tests__/__snapshots__/baseline.test.tsx.snap
components/keyboard/__tests__/__snapshots__/index.test.tsx.snap
components/styles/themes/shared.ts
components/textarea/__tests__/__snapshots__/index.test.tsx.snap
package.json
pages/_app.tsx
pages/en-us/guide/installation.mdx
pages/en-us/guide/server-render.mdx
pages/zh-cn/guide/installation.mdx
pages/zh-cn/guide/server-render.mdx
yarn.lock

feat: optimize fonts rendering on windows

---

pages/en-us/guide/themes.mdx
pages/zh-cn/guide/themes.mdx

docs(themes): fix example code of use-theme

---

examples/create-next-app/package.json

fix create next app yarn

---

next.config.js

Added a short link for icons documentation.

docs: add short link for icons

---

components/select/__tests__/multiple.test.tsx
components/select/select-icon-clear.tsx
components/select/select-multiple-value.tsx
components/select/select.tsx
pages/en-us/components/select.mdx
pages/zh-cn/components/select.mdx

Following #388 
Only missing piece is to update doc in `zh-cn`

feat(select): add clearable option to select multiple with test and english doc

---

README.md

Hi there!
I wanted to suggest a little app that I've created for viewing Near-Earth Objects and the Astronomy Picture of the Day.
Thanks!

chore(showcase): add SentiNEO

---

components/textarea/__tests__/__snapshots__/index.test.tsx.snap
components/textarea/textarea.tsx
pages/en-us/components/textarea.mdx
pages/zh-cn/components/textarea.mdx

Included prop for the textarea which allows setting the resize css value.

feat(textarea): resize prop

---

components/grid/__tests__/__snapshots__/index.test.tsx.snap
components/grid/basic-item.tsx
components/select/__tests__/__snapshots__/multiple.test.tsx.snap

fix: remove unnecessary style in xs grid class

---

package.json
yarn.lock

chore: release v2.1.1

---

components/grid/__tests__/__snapshots__/index.test.tsx.snap
components/grid/basic-item.tsx
components/select/__tests__/__snapshots__/multiple.test.tsx.snap
package.json

fix(grid): fix the invalid property of flex in the default scene

---

components/tabs/__tests__/__snapshots__/index.test.tsx.snap
components/tabs/tabs.tsx

fix(tabs): remove the scrollbar of the tab container

---

components/snippet/snippet.tsx
components/utils/prop-types.ts
pages/en-us/components/snippet.mdx
pages/zh-cn/components/snippet.mdx

ref: https://github.com/geist-org/react/discussions/431#discussioncomment-375795

fix(snippet): fix typo of copy type

---

examples/create-next-app/pages/index.js

fix(typo): gesit -> geist

---

pages/en-us/components/grid.mdx
pages/en-us/components/use-media-query.mdx
pages/zh-cn/components/grid.mdx
pages/zh-cn/components/use-media-query.mdx

docs(breakpoints): upgrade documentatino to match the new theme system

---

components/input/__tests__/__snapshots__/index.test.tsx.snap
components/input/__tests__/__snapshots__/password.test.tsx.snap
components/input/input-icon.tsx
components/table/__tests__/__snapshots__/index.test.tsx.snap
components/table/table-head.tsx
components/toggle/__tests__/__snapshots__/index.test.tsx.snap
components/toggle/toggle.tsx

fix: fix the invalid vertical-align

---

.github/CONTRIBUTING.md

fix(typo): Dodcument -> Do Document

---

README.md

docs: add secret repo as an example

---

pages/en-us/components/display.mdx
pages/zh-cn/components/display.mdx

The image component's width and height attributes receive `number` type.

docs(display): fix image props

---

components/modal/__tests__/index.test.tsx
components/modal/modal.tsx

fix(modal): disable backdrop even if actions missing

---

components/use-click-away/use-click-away.ts

fix: upgrade to be compatible with React-17's event system

---

components/auto-complete/__tests__/__snapshots__/index.test.tsx.snap
components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
components/auto-complete/__tests__/index.test.tsx
components/auto-complete/auto-complete.tsx
pages/en-us/components/auto-complete.mdx
pages/zh-cn/components/auto-complete.mdx

feat(auto-complete): add forwardRef for input element

---

components/avatar/__tests__/__snapshots__/index.test.tsx.snap
components/avatar/avatar.tsx
components/user/__tests__/__snapshots__/index.test.tsx.snap

More details on why it's a good idea:
https://www.w3schools.com/css/css3_object-fit.asp

`object-fit: cover` in Avatar component

---

components/auto-complete/auto-complete.tsx

fix(auto-complete): fix size of loading icon

---

components/auto-complete/auto-complete-dropdown.tsx

fix(auto-complete): hide shadow when no content

---

pages/en-us/components/badge.mdx
pages/en-us/components/display.mdx
pages/zh-cn/components/badge.mdx
pages/zh-cn/components/display.mdx

docs: fix display & badge spacing

---

components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
components/input/__tests__/__snapshots__/index.test.tsx.snap
components/input/__tests__/__snapshots__/password.test.tsx.snap
components/input/input.tsx
components/utils/use-context-state/create-geist-context.tsx

- remove reveal icon for Microsoft Edge
- update snapshot tests
- fix linting for unused-vars
**Current Behavior**
**Expected Behavior**

fix: remove ms-reveal for input

---

components/modal/__tests__/index.test.tsx
components/modal/index.ts
components/modal/modal.tsx
components/modal/use-modal.ts
pages/en-us/components/modal.mdx
pages/zh-cn/components/modal.mdx

feat(modal): responds to keyboard events when modal is displayed

---

lib/components/layout.tsx
lib/components/sidebar/active-catalog.tsx
lib/components/sidebar/active-link.tsx
lib/components/sidebar/tabbar-mobile.tsx

docs: redesign mobile navigation

---

components/avatar/__tests__/__snapshots__/index.test.tsx.snap
components/avatar/avatar.tsx
components/user/__tests__/__snapshots__/index.test.tsx.snap

Remove an unnecessary selector.

fix(avatar): fix margin on first child

---

README.md

chore(showcase): add Regex-Vis

---

components/input/input-props.ts

Renamed hymlType to htmlType in input-props.ts
Fixes #598

fix: Rename hymlType to htmlType

---

lib/components/playground/editor.tsx

fix(playground): hide webkit arrow icon

---

components/button-dropdown/__tests__/__snapshots__/index.test.tsx.snap
components/button-dropdown/__tests__/index.test.tsx
components/button-dropdown/button-dropdown.tsx
pages/en-us/components/button-dropdown.mdx
pages/zh-cn/components/button-dropdown.mdx

feat(button-dropdown): add icon config

---

pages/en-us/components/card.mdx
pages/zh-cn/components/card.mdx

Typo in card component code sample: ceter -> center

fix(docs): typo in card code sample

---

components/tabs/__tests__/__snapshots__/index.test.tsx.snap
components/tabs/tabs-context.ts
components/tabs/tabs-item.tsx
components/tabs/tabs.tsx
pages/en-us/components/tabs.mdx
pages/zh-cn/components/tabs.mdx

feature Add highlight on Tabs component #653

feature Update tabs-item.tsx

---

examples/create-next-app/next-env.d.ts
examples/create-next-app/package.json

Next.js 12 has been released over a month with better performance (https://nextjs.org/blog/next-12). I have updated it to v12.0.4 in the examples.

chore: update create-next-app example to Nextjs 12

---

pages/en-us/guide/installation.mdx

Improves wording around adding font packages
N/A
Improves wording in the documentation about adding additional font packages

chore: update installation.mdx

---

package.json
yarn.lock

- Add `@babel/runtime` to dependencies for ESModule projects. #642 
- Release v2.2.1

chore: release v2.2.1

---

package.json

chore: release v2.2.2

---

examples/create-next-app/.eslintrc.json
examples/create-next-app/next-env.d.ts
examples/create-next-app/next.config.js
examples/create-next-app/package.json
examples/create-next-app/pages/index.tsx
examples/create-next-app/tsconfig.json

chore: update nextjs example

---

package.json
scripts/tsconfig.json

fix: fix reference paths after type compilation

---

package.json

chore: release v2.2.3

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/config.yml
README.md
components/input/__tests__/index.test.tsx
examples/create-next-app/pages/index.tsx
examples/custom-themes/src/theme.js
lib/components/header.tsx
lib/constants.ts
package.json
pages/_app.tsx
pages/en-us/components/badge.mdx
pages/en-us/components/card.mdx
pages/en-us/components/tabs.mdx
pages/en-us/guide/installation.mdx
pages/en-us/guide/introduction.mdx
pages/en-us/guide/themes.mdx
pages/en-us/index.tsx
pages/zh-cn/components/badge.mdx
pages/zh-cn/components/card.mdx
pages/zh-cn/components/tabs.mdx
pages/zh-cn/guide/installation.mdx
pages/zh-cn/guide/introduction.mdx
pages/zh-cn/guide/themes.mdx
pages/zh-cn/index.tsx

chore: rename the GH repository

---

next.config.js

chore: append redirects for project renaming

---

components/input/password.tsx
pages/en-us/components/button-dropdown.mdx
pages/zh-cn/components/button-dropdown.mdx

feat: add scale to password component

---

components/tabs/tabs-context.ts
components/tabs/tabs.tsx
lib/components/menu/menu-sticker.tsx

fix(tabs): fix type of left-space to match component input

---

components/tabs/__tests__/__snapshots__/index.test.tsx.snap
components/tabs/tabs-item.tsx

fix(tabs): fix sub-components ignore theme changes

---

lib/components/layout/layout.tsx
lib/components/layout/menu/menu-links.tsx
lib/components/pures/controls.tsx
pages/_app.tsx

docs: fix the layout of the document site

---

lib/components/layout/layout.tsx
pages/en-us/guide/installation.mdx
pages/zh-cn/guide/installation.mdx

docs: customize separate styles for instalation page

---

components/image/__tests__/__snapshots__/browser.test.tsx.snap
components/link/__tests__/__snapshots__/index.test.tsx.snap
components/link/icon.tsx
components/link/link.tsx
lib/components/mdx-widgets/hybrid-link.tsx
pages/en-us/guide/themes.mdx

fix(links): keep links consistent across typography

---

lib/components/mdx-widgets/hybrid-link.tsx

docs: optimize the determination and rendering of relative url

---

pages/en-us/guide/installation.mdx
pages/zh-cn/guide/installation.mdx

docs: fix tabs layout of install page

---

package.json

chore: release v2.3.0-rc.1

---

components/geist-provider/geist-provider.tsx
components/use-toasts/use-toast.tsx
components/utils/use-geist-ui-context.ts
package.json

chore: release v2.3.0

---

lib/components/layout/menu/menu.tsx

fix: ensure tabs can update handlers when language changes

---

scripts/side-effects.js

docs: set side-effects when build document site

---

package.json

chore: release v2.3.1

---

lib/components/search/search.tsx

docs: fix height of search-box on firefox browser

---

components/pagination/pagination.tsx

fix(pagination): update component context when the total prop changes

---

components/index.ts
package.json

- Export a new tool as an early trial only (will not be added to the documentation, API may still change)
- Export Highlight-related types and tools
- No impact on the user and no accidental increase in package size

chore: export highlight component

---

pages/en-us/guide/installation.mdx
pages/zh-cn/guide/installation.mdx

Addresses #775
- updated the docs, both English and Chinese.

docs: fix next.js installation guide 

---

pages/en-us/guide/scale.mdx
pages/zh-cn/guide/scale.mdx

fix(docs): scale introduce types err

---

pages/en-us/components/tabs.mdx

Updates the button in the final example to show the correct name of the tab.

Update imperative usage tab example button
