- pages/docs/components/spacer.mdx
Both examples have a heading that says "Vertical" even though the second one is clearly horizontal.
> fix: fix heading for Spacer docs

- components/avatar/avatar.tsx
The ``withDefaults<Props, typeof defaultProps>`` caused TypeScript to ignore ``AvatarProps``, which includes the ``ImgHTMLAttributes``.
> fix(avatar): Fix HTML Attributes

- components/avatar/avatar.tsx
When using different elements (`img` / `span`), be as compatible with all attributes as possible.
This means that non `img` attributes do not prompt for errors.
> fix(avatar): fix union types for different elements

- components/utils/use-portal.ts
1. Multiple components may be using shared element slots, destroy a slot can affect other components.
2. Slot is empty and can be reused, no memory waste.
> fix(use-portal): don't remove shared element slot 

- components/select/select-dropdown.tsx
- components/select/select.tsx
- pages/en-us/components/select.mdx
- pages/zh-cn/components/select.mdx
resolved #88 
1. The dropdown-menu has max-height.
2. You can change the max-height by set prop `dropdownClassName` or `dropdownStyle`.
> fix(select): limit the maximum height of the dropdown-menu

- package.json
- rollup.config.js
- scripts/webpack.config.js
- yarn.lock
Optimized bunild scripts, the exprted packages has the follow changes:
- Package of cjs mode is not compressed.
- Support umd mode.
- The size of the user app has not changed.
- User can use `react-devtool` to view all components in development.
- Not the error message will be thrown nromally. (But only in development)
**About the build scripts now:**
- The output of `webpack` contains unnecessary information (`webpack require`), but at present, it is still ubable to switch to `rollup`, refer to [issue from rollup](https://github.com/zeit/styled-jsx/issues/588) .
> build: bundle in cjs mode is not compressed by default

- components/input/use-input.ts
Thanks for nice library!!
I fixed type of `useInput` 's arg.
I think we should be able use `useInput` also in `Textarea` component, and docs introduces use-case for using `useInput` in `Textarea` https://react.zeit-ui.co/en-us/components/textarea#with-useinput
But `bindings.onChange` which is returned by `useInput` can only handle **HTMLInputElement**, so TypeScript throw type errors when I use `useInput` in `Textarea` component.
I fixed it.
> fix: type of useInput

- components/page/__tests__/__snapshots__/child.test.tsx.snap
- components/page/__tests__/__snapshots__/index.test.tsx.snap
- components/page/page.tsx
- lib/components/displays/mock-page.tsx
> fix(page): fix page width too large at md breakpoint

- components/radio/__tests__/__snapshots__/group.test.tsx.snap
- components/radio/__tests__/__snapshots__/index.test.tsx.snap
- components/radio/__tests__/group.test.tsx
- components/radio/__tests__/index.test.tsx
- components/radio/radio-context.ts
- components/radio/radio-description.tsx
- components/radio/radio-group.tsx
- components/radio/radio.tsx
- pages/en-us/components/radio.mdx
- pages/zh-cn/components/radio.mdx
> feat(radio): add support of different sizes

- components/radio/__tests__/__snapshots__/group.test.tsx.snap
- components/radio/radio-context.ts
- components/radio/radio-group.tsx
- components/radio/radio.tsx
> refactor(radio): use CSS variable instead of Context broadcast size

- components/modal/modal.tsx
- pages/en-us/components/modal.mdx
When closing modal without using onClose (closing by click backdrop), body hidden will always be true. This commit fix it.
fixed #237
> fix(modal): set body hidden false on close modal

- components/select/select-dropdown.tsx
- components/select/select-option.tsx
- components/select/select.tsx
- components/shared/dropdown.tsx
- pages/en-us/components/select.mdx
- pages/zh-cn/components/select.mdx
> feat(select): disable dropdown follow parent width

- components/radio/__tests__/__snapshots__/group.test.tsx.snap
- components/radio/__tests__/__snapshots__/index.test.tsx.snap
- components/radio/radio-group.tsx
> fix(radio): fix style imbalance caused by decimal width

- components/auto-complete/__tests__/__snapshots__/index.test.tsx.snap
- components/auto-complete/__tests__/index.test.tsx
- components/auto-complete/__tests__/search.test.tsx
- components/auto-complete/auto-complete-item.tsx
- components/auto-complete/auto-complete.tsx
- pages/en-us/components/auto-complete.mdx
- pages/zh-cn/components/auto-complete.mdx
> feat(auto-complete): add control for free solo

- components/shared/__tests__/backdrop.test.tsx
- components/shared/backdrop.tsx
> fix(backdrop): fix click events from content to close modal unexpectedly

- components/image/__tests__/browser.test.tsx
- components/image/image-browser.tsx
- pages/en-us/components/image.mdx
- pages/zh-cn/components/image.mdx
> feat(image): pass through all props of anchor element

- components/css-baseline/__tests__/__snapshots__/baseline.test.tsx.snap
- components/css-baseline/css-baseline.tsx
> feat(baseline): optimize fontSize of block code

- components/snippet/__tests__/__snapshots__/index.test.tsx.snap
- components/snippet/__tests__/index.test.tsx
- components/snippet/snippet.tsx
- pages/en-us/components/snippet.mdx
> feat(snippet): add custom symbol and toast

- components/auto-complete/auto-complete-item.tsx
- components/auto-complete/auto-complete.tsx
- pages/en-us/components/auto-complete.mdx
- pages/zh-cn/components/auto-complete.mdx
> fix(auto-complete): fix the height of custom options

- components/popover/popover-item.tsx
- components/popover/popover.tsx
- **Popover**: add default `portalClassName`
- **Popover.Item**: add default `className`
> fix(popover): fix the undefined classname

- components/tabs/__tests__/__snapshots__/index.test.tsx.snap
- components/tabs/tabs.tsx
Add `role="button"` to tabs, vercel style has the `role` attribute. This also [make vimium recognize the tab](https://github.com/philc/vimium/blob/bdf654aebe6f570f427c5f7bc9592cad86e642b5/content_scripts/link_hints.js#L912).
By the way, what does the "Label has been added" checkbox mean?
> fix(tabs): add role="button" to tab for a11y

- components/modal/__tests__/__snapshots__/index.test.tsx.snap
- components/modal/modal-action.tsx
- components/modal/modal-actions.tsx
- pages/en-us/components/modal.mdx
- pages/zh-cn/components/modal.mdx
> feat(modal): use Button to reconstrust Modal.Action

- components/popover/popover-item.tsx
> style(popover-item): the whole item should be clickable when using with link

- components/modal/modal-action.tsx
> fix(modal): fix type of Modal.Action

- components/button-group/__tests__/__snapshots__/index.test.tsx.snap
- components/button/__tests__/__snapshots__/icon.test.tsx.snap
- components/button/button.tsx
- components/modal/__tests__/__snapshots__/index.test.tsx.snap
- components/modal/__tests__/index.test.tsx
- components/modal/modal-action.tsx
- components/modal/modal-wrapper.tsx
- components/shared/backdrop.tsx
- components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
- components/utils/collections.ts
> feat(modal): lock tab action inside modal

- components/page/__tests__/__snapshots__/child.test.tsx.snap
- components/page/page-footer.tsx
Currently `Page.Footer` is too wide comparing to other Page subcomponents. This PR makes footer's width to respect padding of root Page component (theme.layout.gap) which substracted twice from 100% fixes the problem.
> fix(page): fix page footer width

- pages/en-us/components/use-clipboard.mdx
Fixed the naming from `useClickAway` to `useClipboard` in the docs for clipboard.
> docs: fix useClipboard text

- components/tabs/__tests__/__snapshots__/index.test.tsx.snap
- components/tabs/tabs.tsx
- lib/components/menu/menu-sticker.tsx
- pages/en-us/components/tabs.mdx
- Added overflow to tabs
- Hid scrollbar on tabs
- Made menu sticker compatible with scrollable tabs by assigning correct width
- Added scroll behavior example in docs (english)
- Tab labels now no longer breaks on multiple lines
> Tabs scrollable

- .github/workflows/publish.yml
The `dist-tag` information is now automatically added when the package is published, this will help to improve the version semantics of the current library.
1. Will does not install `canary` by default: `yarn add @geist-ui/react`.
2. Specify `next` before install the `canary` version: `yarn add @geist-ui/react@next`.
> ci: auto add dist-tag when publish package

- pages/en-us/components/grid.mdx
tiny fix to correct the description of the default value of the `direction` prop of `Grid`
> fix default value of direction prop

- .github/CONTRIBUTING.md
Spectrum Chat is going `read-only` being replaced by Github Discussions.
> chore(docs): update spectrum link with github discussions

- components/loading/__tests__/__snapshots__/index.test.tsx.snap
- components/loading/__tests__/index.test.tsx
- components/loading/loading.tsx
- pages/en-us/components/loading.mdx
- pages/zh-cn/components/loading.mdx
Solves #488 
In the file : [Loading.tsx](https://github.com/geist-org/react/tree/master/components/loading)
There are `width` and `height` props being passed but they don't seem to be used anywhere, furthermore `width` & `height` are calculated based on the `size` props which decided the actual size of the Loading Component.
After : 
Added a Test Case for `width` and `height` and Updated Snapshots.
Let me know if Changes Needed ✨
> feat(loading): apply width & height props

- components/fieldset/__tests__/__snapshots__/index.test.tsx.snap
- components/fieldset/fieldset-subtitle.tsx
- components/fieldset/fieldset-title.tsx
`FieldsetSubtitle` and `FieldsetTitle` use inline element `p` and `h4`, but as a container element, user may insert block element in these two container, which will cause `Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.`
> fix: fieldset title/subtitle use block element

- components/button-dropdown/__tests__/__snapshots__/index.test.tsx.snap
- components/button-dropdown/button-dropdown.tsx
> fix: fix the style of button-dropdown

- components/css-baseline/css-baseline.tsx
- components/grid/grid-container.tsx
- components/grid/grid.tsx
- components/modal/modal-action.tsx
- lib/components/icons/logo.tsx
- package.json
- tests/__mocks__/styled-jsx/css.js
- yarn.lock
Fix for #519
Update styled-jsx to ^3.3.1 to allow compatibility with react@^17
> chore(deps): update styled-jsx to ^3.3.1

- tsconfig.json
Resolve build failures similar to #524 . (Disable NextJS from checking for unwanted folders at build time)
> build: ignore the example folder when build document site

- components/css-baseline/__tests__/__snapshots__/baseline.test.tsx.snap
- components/css-baseline/css-baseline.tsx
Would Boost Light House Scores 🚀
> fix: deprecated pseudo element selector

- components/auto-complete/auto-complete-dropdown.tsx
- components/auto-complete/auto-complete.tsx
- components/shared/dropdown.tsx
- pages/en-us/components/auto-complete.mdx
- pages/zh-cn/components/auto-complete.mdx
From #534 , thanks to @Bowen7 .
This is a feature that was delayed due to the refactoring of the size property and is now merged into the new canary version.
> feat(auto-complete): add props for popup container

- components/select/__tests__/__snapshots__/index.test.tsx.snap
- components/select/__tests__/__snapshots__/multiple.test.tsx.snap
- components/select/__tests__/events.test.tsx
- components/select/__tests__/index.test.tsx
- components/select/index.ts
- components/select/select-dropdown.tsx
- components/select/select-input.tsx
- components/select/select-option.tsx
- components/select/select.tsx
- components/select/styles.ts
- components/shared/dropdown.tsx
- pages/en-us/components/select.mdx
- pages/zh-cn/components/select.mdx
- When `blur` is called, Select loses focus and closes the dropdown element.
- When `focus` is called, Select gets focus but does not open the dropdown element.
- The scrollTo function only works after the `onDropdownVisibleChange` event has been triggered, because before that, the dropdown had not yet started rendering.
- Tab presses trigger the focus event correctly, however, no more keyboard event interactions are currently added.
> feat(select): imporve the focus events to export simulated ref

- pages/zh-cn/components/input.mdx
Change `status="secondary"` to `type="secondary"` in the `input` component doc.
> fix(docs): components/input types not working in zh-CN docs

- components/select/select-option.tsx
Fixes #613.
The box dimensions of the `Select.Option` component was not taking spacing into consideration. Declaring the box sizing fits the option inside the select dropdown.
| `master` | This PR |
| --------- | -------- |
| ![image](https://user-images.githubusercontent.com/26530524/144952123-04329dd3-393d-4b00-b5a1-40d35a90bdf1.png) | ![image](https://user-images.githubusercontent.com/26530524/144952097-75da58a3-ec7b-4adb-ad68-d1359eef0f48.png) |
> fix(select): option horizontal overflow

- components/select/select-input.tsx
- components/table/table-column.tsx
- components/table/table-head.tsx
- components/tabs/tabs-item.tsx
- components/tooltip/tooltip.tsx
- components/tree/tree-folder-icon.tsx
This PR fixes #611 typos on some components' `displayName`
> fix: components' `displayName` typos

- components/grid/__tests__/__snapshots__/index.test.tsx.snap
- components/grid/basic-item.tsx
- components/select/__tests__/__snapshots__/multiple.test.tsx.snap
Because the grid styles use Mobile First, the "@media only screen and (max-width: $ {theme.breakpoints.xs.max})" breakpoint is unnecessary. This generates the same styles and is applied in the same sizes as the ".xs" class.
I have removed the media query "@media only screen and (max-width: $ {theme.breakpoints.xs.max})". I have tested the component with and without this "media query" and I get the same results.
> fix: Removed unnecessary code in Grid Component

- package.json
- scripts/fix-styled-jsx.js
- scripts/rollup.config.js
- yarn.lock
- Use Rollup bundle all components (`cjs & esm`)
- Remove all dependencies of the component library
- Fix module export error of `styled-jsx` after `rollup` packaged
- Reducing the output size of component library
> build: bundle all components with rollup instead of webpack

- examples/create-next-app/pages/index.tsx
Have been getting an annoying warning message from eslint:
`Image elements must have an alt prop, either with meaningful text, or an empty string for decorative images.eslintjsx-a11y/alt-text`
> fix: Add alt text for image to avoid eslint warn

- components/css-baseline/css-baseline.tsx
- package.json
- typings/styled.d.ts
- Simplify the type of export within a component
- Remove the type from `styled-jsx` (there is only one reference)
> chore: simplify the type srouce of third-party lib

- components/page/__tests__/__snapshots__/index.test.tsx.snap
- components/page/__tests__/index.test.tsx
- components/page/page.tsx
- pages/en-us/components/page.mdx
- pages/zh-cn/components/page.mdx
> feat(page): add props to control the style of dot

- components/button/__tests__/__snapshots__/icon.test.tsx.snap
- components/button/button.tsx
- components/modal/__tests__/__snapshots__/index.test.tsx.snap
Slightly reduce the default `width` of the `Button` to avoid imbalance when over-scaling.
> feat(button): slightly reduce the default width

- components/geist-provider/geist-provider.tsx
- components/index.ts
- components/snippet/snippet.tsx
- components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
- components/use-toasts/__tests__/index.test.tsx
- components/use-toasts/helpers.tsx
- components/use-toasts/index.ts
- components/use-toasts/toast-container.tsx
- components/use-toasts/toast-item.tsx
- components/use-toasts/use-toast.tsx
- components/utils/use-geist-ui-context.ts
- lib/components/customization/codes.tsx
- lib/components/mdx-widgets/colors/index.tsx
- lib/components/playground/editor.tsx
- pages/en-us/components/file-tree.mdx
- pages/en-us/hooks/use-clipboard.mdx
- pages/en-us/hooks/use-toast.mdx
- pages/zh-cn/components/file-tree.mdx
- pages/zh-cn/hooks/use-clipboard.mdx
- pages/zh-cn/hooks/use-toast.mdx
- Add `placement` support.
- Add `ReactNode` support.
- Allow users to modify the global style of Toast. (`useToast(styles)`)
- Users can query the instance of Toast according to the specified ID and can manipulate the methods on the instance.
- Greatly optimized for Toast performance and stability.
> feat(toast): redesign hooks to compatible with placement and styles

- components/drawer/__tests__/__snapshots__/index.test.tsx.snap
- components/drawer/__tests__/use-modal.test.tsx
- components/modal/__tests__/__snapshots__/index.test.tsx.snap
- components/modal/modal.tsx
- components/shared/__tests__/__snapshots__/backdrop.test.tsx.snap
- components/shared/__tests__/backdrop.test.tsx
- components/shared/backdrop.tsx
- components/use-modal/__tests__/use-modal.test.tsx
- lib/components/search/search.tsx
- Adds more class-names compatibility to the Modal component, extending the interface downwards, which does not affect the existing behavior. Release these again in the next canary version.
> fix(search): remove global override of search styles

- components/use-click-away/__tests__/click-away.test.tsx
- components/use-click-away/use-click-away.ts
- pages/en-us/hooks/use-click-away.mdx
- pages/zh-cn/hooks/use-click-away.mdx
1. The `handler` should be updated if changed.
2. replace `Event` with `MouseEvent`
> fix(use-click-away): update handler reference

- components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
- components/input/__tests__/__snapshots__/index.test.tsx.snap
- components/input/__tests__/__snapshots__/password.test.tsx.snap
- components/input/input.tsx
issue [#726](https://github.com/geist-org/geist-ui/issues/726)
> fix(input): remove fixed height of label container

- components/index.ts
- components/input/__tests__/password.test.tsx
- components/input/password.tsx
- components/use-scale/__tests__/scale.test.tsx
- components/use-scale/scale-context.ts
- components/use-scale/utils.ts
- components/use-scale/with-scale.tsx
In the last update, Geist removed all scale-related props from within the component to avoid side effects, but this resulted in the internal wrapper component (e.g. `Input.Password`) no longer being able to pass them, and now a new function has been added to make it easier for the internal wrapper component to get native scale values.
2 test cases have also been added to check the behavior of passing native scale props.
> fix(password): pass all scale props for internally wrapped components

- components/button-dropdown/__tests__/__snapshots__/index.test.tsx.snap
- components/button-dropdown/button-dropdown.tsx
- components/css-baseline/__tests__/__snapshots__/baseline.test.tsx.snap
- components/css-baseline/css-baseline.tsx
- package.json
> fix(button-dropdown): remove the default style and side effects under webkit

- package.json
- scripts/rollup.config.js
> fix(build): remove source-map files generated by babel

- pages/en-us/guide/installation.mdx
> fix: en-us document linked to zh-cn document

- pages/en-us/guide/server-render.mdx
- pages/zh-cn/guide/server-render.mdx
**Description**
Currently, the guide for Next.js in Server Render gives a type error after updating `@types/react` to `^18.0.0`. The overwrite of styles seems to be causing trouble. The `styles` are of type `styles?: ReactFragment | ReactElement<any, string | JSXElementConstructor<any>>[] | undefined instead of JSX.Element`.
**Screenshots**
> docs(guide): update nextjs guide for @types/react

- pages/en-us/components/table.mdx
- pages/zh-cn/components/table.mdx
Small typo, replaced `reocrds` by `records` in the documentation of the table component.
> fix(docs): correct typo in table component

- lib/components/mdx-widgets/colors/colors-data.ts
Correcting typo `Violet` -> `Magenta` in `highlight`.
> fix(docs): correct wrong color data: `Violet` -> `Magenta`

- pages/en-us/guide/installation.mdx
- pages/zh-cn/guide/installation.mdx
- Add missing apostrophes to inter import
because it cant work like this:
> fix: add missing apostrophes to inter import
